version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: pydocstyle
    versions:
    - 5.1.1
